#!/bin/sh

# Path to this script.
appended_relative=$(dirname "$0" ; echo x)
sanitized_relative=${appended_relative%??}
appended_absolute="$( cd "$sanitized_relative" && pwd; echo x)"
sanitized_absolute=${appended_absolute%??}

cd "${sanitized_absolute}"

rm -rf build/ CMakeCache.txt CMakeFiles/ cmake_install.cmake Makefile build.ninja rules.ninja *.xcodeproj *.build CMakeScripts cmake_log.txt

if [ -d "AlloSystem" ]; then
  cd AlloSystem
    ./distclean
  cd ..
fi

if [ -d "GLV" ]; then
  cd GLV
    ./distclean
  cd ..
fi

if [ -d "Gamma" ]; then
  cd Gamma
    ./distclean
  cd ..
fi

if [ -d "vsr" ]; then
  cd vsr
    ./distclean
  cd ..
fi
