#! /bin/sh

rm -rf build/ CMakeCache.txt CMakeFiles/ cmake_install.cmake cmake_log.txt Makefile build.ninja rules.ninja *.xcodeproj *.build CMakeScripts cmake_log.txt

cd AlloProject
  rm -rf build/ cmake_log.txt
cd ..

if [ -d "AlloSystem" ]; then
  cd AlloSystem
    ./distclean
  cd ..
fi

if [ -d "GLV" ]; then
  cd GLV
    ./distclean
  cd ..
fi

if [ -d "Gamma" ]; then
  cd Gamma
    ./distclean
  cd ..
fi

if [ -d "vsr" ]; then
  cd vsr
    ./distclean
  cd ..
fi
